name: pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: pacman -Syu --noconfirm clang python-pip git
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: clang-format --version
      - run: uv sync --dev
      - run: uv run --dev pre-commit run --all-files --verbose
